# basic pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "autoencoder_vad"
version = "0.1.0"
description = ""
authors = ["igdtuw <[email protected]>"]
